name: Build and Test

on:
  workflow_call:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ github.token }}
    - name: Install Homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Run Test Task
      run: task test
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}
    - name: .NET Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Tests
        path: testresults/*.trx
        reporter: dotnet-trx
        fail-on-empty: false
    - name: JUnit Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Tests
        path: jest-junit.xml
        reporter: jest-junit
        fail-on-empty: false
    - name: Check Code Coverage Report
      uses: andstor/file-existence-action@v3
      if: success() || failure()
      id: check_coverage_report
      with:
        files: testresults/**/coverage.cobertura.xml
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      if: steps.check_coverage_report.outputs.files_exists == 'true'
      with:
        filename: testresults/**/coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        indicators: true
        output: both
        thresholds: '40 70'
    - name: Write to Job Summary
      if: steps.check_coverage_report.outputs.files_exists == 'true'
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY